### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by Freddy03h**
- update dependencies
- fix some warning and issues
- format command for reason files
- refactor TextLink and create TouchableHighlightLink

### CODE REVIEW

**Comment by Freddy03h** [comment]
Upgrade to `reason-react@^0.7.0` and start to use next version of `bs-react-native` called `reason-react-native`

**Comment by Freddy03h** [comment]
Upgraded to first official release of `reason-react-native`

**Comment by Freddy03h** [comment]
Hi, can you have a look please @kgoggin ?

**Comment by kgoggin** [comment]
Hey @Freddy03h sorry for not looking at this sooner. Thanks for updating all the things!

**Pull request merged**
